sonar.projectKey=Youssefouiiza_New_audit
sonar.organization=youssefouiiza
sonar.projectName=Audit Platform

sonar.sources=backend/src/main,frontend/src,audit_rag_maroc
sonar.tests=backend/src/test,frontend/src,audit_rag_maroc
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/test_*.py
sonar.java.binaries=backend/target/classes
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/.next/**,**/.coverage
sonar.sourceEncoding=UTF-8

# Coverage Reporting Paths
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=audit_rag_maroc/coverage.xml
