name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build Backend
        run: |
          cd backend
          mvn -B clean compile

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ 0a37c0c08e37e8ae67cdb394aae2c94fdf4a25c3 }}
          SONAR_TOKEN: ${{ 0a37c0c08e37e8ae67cdb394aae2c94fdf4a25c3 }}
        with:
          args: >
            -Dsonar.projectKey=audit-platform
            -Dsonar.organization=youssefouiiza
            -Dsonar.sources=backend/src/main,frontend/src
            -Dsonar.java.binaries=backend/target/classes
            -Dsonar.host.url=https://sonarcloud.io
